# Generated by Django 4.0.5 on 2022-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200, unique=True)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_author', models.CharField(max_length=40)),
            ],
        ),
    ]
